---
title: "<font size='3'>An introduction to</font>"
subtitle: "`tidyverse`"
author: "<a href='https://github.com/AEBilgrau'>Anders Ellern Bilgrau</a>"
date: "<font size='3'>User group meeting 2019-01-28</font><br><font size='1'>(last updated: `r Sys.Date()`)</font>"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false




---
```{r setup, include=FALSE}
set.seed(521924934)
options(htmltools.dir.version = FALSE,
        width = 80)
pkggraph::init(local = TRUE)
knitr::opts_chunk$set(
  comment = "",
  size = "small",
  dev = "svg",
  fig.align = "center",
  fig.path = "figs/"
)

#https://www.garrickadenbuie.com/blog/2018/01/23/highlight-lines-without-breaking-the-code-in-xaringan/
hook_source <- knitr::knit_hooks$get('source')
knitr::knit_hooks$set(source = function(x, options) {
  x <- stringr::str_replace(x, "^[[:blank:]]?([^*].+?)[[:blank:]]*#<<[[:blank:]]*$", "*\\1")
  hook_source(x, options)
})
```


```{r tidyverse, child = "input/tidyverse.Rmd"}
```

---

```{r tibble, child = "input/tibble.Rmd"}
```

---

```{r readr, child = "input/readr.Rmd"}
```

---

```{r dplyr, child = "input/dplyr.Rmd"}
```

---

```{r tidyr, child = "input/tidyr.Rmd"}
```

---

```{r purrr, child = "input/purrr.Rmd"}
```

---

```{r stringr, child = "input/stringr.Rmd"}
```

---

```{r ggplot2, child = "input/ggplot2.Rmd"}
```

---
class: inverse, center, middle

# More help

.left[
* Within R studio: `Help > Cheatsheet`
* The [R for Data Science](https://r4ds.had.co.nz/) book [1]
]

.footnote[
[1] https://r4ds.had.co.nz/
]

???

Again searching the internet gets you help nearly all the time.


